image: node:latest
cache:
  paths:
  - vendor/

pages:
  stage: deploy
  script:
  - npm install
  - ./node_modules/.bin/docpress build
  - mkdir public
  - cp -rf _docpress/* public/
  artifacts:
    paths:
    - public
  only:
  - master
