image: node:8-alpine
cache:
  paths:
  - vendor/

pages:
  image: node:alpoine
  stage: deploy
  script:
  - npm install -g docpress
  - docpress build
  - mkdir public
  - cp docpress/* public/
  artifacts:
    paths:
    - public
  only:
  - master
